### ISSUE TITLE
Dropdatabase is undefined

### ISSUE THREAD

**Issue by ecasilla** [SamVerschueren/mongoose-seeder#6]
node_modules/mongoose-seeder/lib/mongoose-seeder.js:258
                mongoose.connection.db.dropDatabase(function(err) {
                                      ^
TypeError: Cannot read property 'dropDatabase' of undefined

**Comment by SamVerschueren** [comment]
Hi @ecasilla 

This is not really well documented but I guess that the problem is that you are not waiting for mongoose to be connected with the database.

Can you try something like this and let me know if it fixes the problem? If so, I will update the documentation.

``` javascript
mongoose.connect(config, options);

mongoose.connection.on('connected', function() {
    seeder.seed(data);
});
```

Thanks

**Comment by SamVerschueren** [comment]
Closed due to no response.

Please reopen if you still experience the problem.
